# Generated by Django 2.0.2 on 2018-12-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
