# Generated by Django 2.0.2 on 2018-12-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_fav_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategory',
            old_name='parent_categroy',
            new_name='parent_categry',
        ),
    ]
