# Generated by Django 2.0.2 on 2018-12-25 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181225_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategory',
            old_name='parent_categry',
            new_name='parent_category',
        ),
    ]
