# Generated by Django 2.0.2 on 2018-12-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181225_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='imagte',
        ),
    ]
