# Generated by Django 2.0.2 on 2019-01-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20181225_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品类别1', 'verbose_name_plural': '商品类别1'},
        ),
    ]
