# Generated by Django 2.0.2 on 2018-12-25 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20181225_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcar',
            old_name='goods_num',
            new_name='nums',
        ),
    ]
